import "./globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import ClientOnly from "@/utils/client-only";
import { ToasterProvider } from "@/providers/toaster-provider";

import LoginModal from "@/components/modals/login-modal";
import RegisterModal from "@/components/modals/register-modal";
import ActivateUserModal from "@/components/modals/activate-user-modal";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          <ActivateUserModal />
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
